name: CI
on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Lint Markdown files
        uses: actionshub/markdownlint@v3.1.3

      - name: Lint YAML files
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Build image
        run: docker build -f Dockerfile .
